Modify fypp workflow to fail if ftorch.f90 does not match expected result of ftorch.fypp on every push.

diff --git a/.github/workflows/fypp.yml b/.github/workflows/fypp.yml
--- a/.github/workflows/fypp.yml
+++ b/.github/workflows/fypp.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   various:
-    name: FYPP checks - run pre-commit hook in repo
+    name: FYPP checks - runs check on fypp and f90 files
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -15,6 +15,13 @@ jobs:
         python-version: "3.11"
     - run: pip install fypp
 
-    - name: Check pre-commit hook
-      run: chmod +x pre-commit
-           ./pre-commit
+    - name: Check fypp matches f90
+      run: |
+        fypp src/ftorch.fypp src/temp.f90_temp
+        if ! diff -q src/ftorch.f90 src/temp.f90_temp; then
+          echo "Error: The code in ftorch.f90 does not match that expected from ftorch.fypp."
+          echo "Please re-run fypp on ftorch.fypp to ensure consistency and re-commit."
+          exit 1
+        else
+          exit 0
+        fi
