Merge LFortran workflow into Flang one and rename LLVM

diff --git a/.github/workflows/test_suite_ubuntu_cpu_llvm.yml b/.github/workflows/test_suite_ubuntu_cpu_llvm.yml
--- a/.github/workflows/test_suite_ubuntu_cpu_llvm.yml
+++ b/.github/workflows/test_suite_ubuntu_cpu_llvm.yml
@@ -1,4 +1,4 @@
-# Workflow to run the FTorch test suite using jobs for LFortran compiler
+# Workflow to run the FTorch test suite using jobs for LLVM-based compilers
 name: Test suite (Ubuntu CPU)
 
 # Controls when the workflow will run
@@ -10,7 +10,7 @@ on:
   # Triggers the workflow on pushes to open pull requests with changes to this workflow
   pull_request:
     paths:
-      - '.github/workflows/test_suite_ubuntu_cpu_lfortran.yml'
+      - '.github/workflows/test_suite_ubuntu_cpu_llvm.yml'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -26,13 +26,17 @@ permissions: {}
 # Workflow run - one or more jobs that can run sequentially or in parallel
 jobs:
   test-suite:
-    name: lfortran ${{ matrix.flang_version }}, ${{ matrix.standard }}
+    name: ${{ matrix.compiler }} ${{ matrix.flang_version }}, ${{ matrix.standard }}
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
+        compiler: [flang, lfortran]
+        std: [f2018]
         flang_version: [21]
+        pfunit_longversion: [4.18.2]
+        pfunit_shortversion: [4.18]
 
     # Terminate the job if it runs for more than 15 minutes
     timeout-minutes: 15
@@ -65,6 +69,7 @@ jobs:
           pip install . --extra-index-url https://download.pytorch.org/whl/cpu --group test
 
       - name: Install LFortran
+        if: ${{ matrix.compiler == 'lfortran' }}
         run: |
           . ftorch/bin/activate
           sudo apt-get install build-essential binutils-dev
@@ -75,15 +80,29 @@ jobs:
           export CMAKE_PREFIX_PATH_LFORTRAN=$(pwd)/build
           ./build0.sh
           ./build1.sh
+          echo "export PATH="$(pwd)/lfortran/src/bin:\${PATH}" >> ftorch/bin/activate
 
       - name: Install OpenMPI
         run: |
           sudo apt update
           sudo apt install -y openmpi-bin openmpi-common libopenmpi-dev
 
-      - name: Build FTorch
+      - name: Install pFUnit
+        if: ${{ matrix.compiler == 'flang' }}
         run: |
-          export PATH="$(pwd)/lfortran/src/bin:${PATH}"
+          # TODO: Avoid version pinning (needed because version appears in install path)
+          git clone -b "v${{ matrix.pfunit_longversion }}" https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
+          mkdir pFUnit/build
+          cd pFUnit/build
+          cmake ..\
+            -DCMAKE_Fortran_COMPILER="flang-${{ matrix.flang_version }}" \
+            -DMPI_Fortran_COMPILER=mpif90
+          make -j 4 install
+
+      - name: Build FTorch
+        env:
+          FORTRAN_STANDARD: ${{ matrix.std }}
+        run: |
           . ftorch/bin/activate
           VN=$(python -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
           export Torch_DIR=${VIRTUAL_ENV}/lib/python${VN}/site-packages
@@ -94,76 +113,92 @@ jobs:
           mkdir -p ${INSTALL_DIR}
           cd ${BUILD_DIR}
 
+          if [ "${{ matrix.compiler }}" == "flang" ]; then
+            # NOTE: The pFUnit version (pinned during installation above) is used in the install path.
+            PFUNIT_DIR="$(pwd)/pFUnit/build/installed/PFUNIT-${{ matrix.pfunit_shortversion }}"
+            PREFIX="${PFUNIT_DIR};${Torch_DIR}"
+            FFLAGS="-std=${FORTRAN_STANDARD}"
+          else
+            PREFIX="${Torch_DIR}"
+            FFLAGS=""
+          fi
+
           cmake .. \
             -DPython_EXECUTABLE="$(which python)" \
             -DCMAKE_BUILD_TYPE=Release \
-            -DCMAKE_Fortran_COMPILER=lfortran \
+            -DCMAKE_Fortran_COMPILER="flang-${{ matrix.flang_version }}" \
             -DCMAKE_C_COMPILER=clang  \
             -DCMAKE_CXX_COMPILER=clang++  \
             -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
             -DCMAKE_BUILD_TESTS=TRUE \
-            -DCMAKE_PREFIX_PATH="${Torch_DIR}"
+            -DCMAKE_PREFIX_PATH="${PREFIX}" \
+            -DCMAKE_Fortran_FLAGS="${FFLAGS}"
           cmake --build .
           cmake --install .
 
-      # TODO: Re-enable pkg-config
-      # - name: Check pkg-config file
-      #   run: |
-      #     # pkg-config looks in the `build` directory for libraries
-      #     export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:build
+      - name: Check pkg-config file
+        run: |
+          # pkg-config looks in the `build` directory for libraries
+          export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:build
 
-      #     libs=$(pkg-config --libs ftorch)
-      #     cflags=$(pkg-config --cflags ftorch)
+          libs=$(pkg-config --libs ftorch)
+          cflags=$(pkg-config --cflags ftorch)
 
-      #     # Assert linker flags not empty
-      #     if [[ -z "${libs}" ]]
-      #     then
-      #       echo "::error ::pkg-config --libs ftorch returned empty output"
-      #       exit 1
-      #     fi
+          # Assert linker flags not empty
+          if [[ -z "${libs}" ]]
+          then
+            echo "::error ::pkg-config --libs ftorch returned empty output"
+            exit 1
+          fi
 
-      #     # Assert expected linker flags
-      #     lib_dir=$(grep -oE "\-L.*/lib" <<< ${libs})
-      #     lib=$(grep -oE "\-lftorch" <<< ${libs})
-      #     if [[ -z "${lib_dir}" || -z "${lib}" ]]
-      #     then
-      #       echo "::error ::pkg-config --libs ftorch do not contain expected linker flags"
-      #       exit 1
-      #     fi
+          # Assert expected linker flags
+          lib_dir=$(grep -oE "\-L.*/lib" <<< ${libs})
+          lib=$(grep -oE "\-lftorch" <<< ${libs})
+          if [[ -z "${lib_dir}" || -z "${lib}" ]]
+          then
+            echo "::error ::pkg-config --libs ftorch do not contain expected linker flags"
+            exit 1
+          fi
 
-      #     # Assert compiler flags not empty
-      #     if [[ -z "${cflags}" ]]
-      #     then
-      #       echo "::error ::pkg-config --cflags ftorch returned empty output"
-      #       exit 1
-      #     fi
+          # Assert compiler flags not empty
+          if [[ -z "${cflags}" ]]
+          then
+            echo "::error ::pkg-config --cflags ftorch returned empty output"
+            exit 1
+          fi
 
-      #     # Assert expected compiler flags
-      #     include_dir=$(grep -oE "/include " <<< ${cflags})
-      #     module_dir=$(grep -oE "/include/ftorch" <<< ${cflags})
-      #     if [[ -z ${include_dir} || -z ${module_dir} ]]
-      #     then
-      #         echo "::error ::pkg-config --cflags ftorch do not contain expected compiler flags"
-      #         exit 1
-      #     fi
+          # Assert expected compiler flags
+          include_dir=$(grep -oE "/include " <<< ${cflags})
+          module_dir=$(grep -oE "/include/ftorch" <<< ${cflags})
+          if [[ -z ${include_dir} || -z ${module_dir} ]]
+          then
+              echo "::error ::pkg-config --cflags ftorch do not contain expected compiler flags"
+              exit 1
+          fi
+
+      - name: Run Fortran unit tests
+        if: ${{ matrix.compiler == 'flang' }}
+        run: |
+          . ftorch/bin/activate
+          cd build
+          ctest --verbose --tests-regex unit
 
       - name: Run Python unit tests
         run: |
-          export PATH="$(pwd)/lfortran/src/bin:${PATH}"
           . ftorch/bin/activate
           pytest --verbose test/ftorch_utils
 
       - name: Run integration tests
         run: |
-          export PATH="$(pwd)/lfortran/src/bin:${PATH}"
           . ftorch/bin/activate
           cd build
           ctest --verbose --tests-regex example
 
         # Check that we can successfully build and run an example outside the main FTorch build process
       - name: Standalone SimpleNet example
+        env:
+          FORTRAN_STANDARD: ${{ matrix.std }}
         run: |
-          export PATH="$(pwd)/lfortran/src/bin:${PATH}"
           . ftorch/bin/activate
           VN=$(python -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
           export Torch_DIR="${VIRTUAL_ENV}/lib/python${VN}/site-packages/torch"
@@ -175,6 +210,7 @@ jobs:
             -DPython_EXECUTABLE="$(which python)" \
             -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_PREFIX_PATH="${FTORCH_INSTALL_DIR};${Torch_DIR}" \
-            -DCMAKE_BUILD_TESTS=TRUE
+            -DCMAKE_BUILD_TESTS=TRUE \
+            -DCMAKE_Fortran_FLAGS="-std=${FORTRAN_STANDARD}"
           cmake --build .
           ctest -V
