Separate out build systems for CMake and fpm

diff --git a/.github/workflows/test_suite_ubuntu_cpu_gnu.yml b/.github/workflows/test_suite_ubuntu_cpu_gnu.yml
--- a/.github/workflows/test_suite_ubuntu_cpu_gnu.yml
+++ b/.github/workflows/test_suite_ubuntu_cpu_gnu.yml
@@ -47,6 +47,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        build_system: [cmake, fpm]
         std: ["f2008", "f2018"]
         gcc_version: [9, 10, 11, 12, 13]
         pfunit_version: ["4.12.0", "4.18.2"]
@@ -109,6 +110,7 @@ jobs:
 
       # TODO: Add pip package to Python dependencies once https://github.com/fortran-lang/fpm/pull/1250 merged
       - name: Build fpm
+        if: ${{ matrix.build_system == fpm }}
         run: |
           git clone -b fix/1226-link-flag-propagation https://github.com/ijatinydv/fpm.git
           cd fpm
@@ -120,48 +122,57 @@ jobs:
           sudo apt update
           sudo apt install -y openmpi-bin openmpi-common libopenmpi-dev
 
-      # TODO: Re-enable unit tests
-      # - name: Install pFUnit
-      #   run: |
-      #     # TODO: Avoid version pinning (needed because version appears in install path)
-      #     git clone -b v4.12.0 https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
-      #     mkdir pFUnit/build
-      #     cd pFUnit/build
-      #     cmake ..\
-      #       -DCMAKE_Fortran_COMPILER=gfortran\
-      #       -DMPI_Fortran_COMPILER=mpif90
-      #     make -j 4 install
+      - name: Install pFUnit
+        if: ${{ matrix.build_system == cmake }}
+        run: |
+          # TODO: Avoid version pinning (needed because version appears in install path)
+          git clone -b v4.12.0 https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
+          mkdir pFUnit/build
+          cd pFUnit/build
+          cmake ..\
+            -DCMAKE_Fortran_COMPILER=gfortran\
+            -DMPI_Fortran_COMPILER=mpif90
+          make -j 4 install
 
-      - name: Build FTorch
+      - name: Build FTorch with CMake
+        if: ${{ matrix.build_system == cmake }}
         env:
           FORTRAN_STANDARD: ${{ matrix.std }}
         run: |
           . ftorch/bin/activate
           VN=$(python -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
           export Torch_DIR=${VIRTUAL_ENV}/lib/python${VN}/site-packages/torch
-          # TODO: Re-enable CMake build system
-          # export BUILD_DIR=$(pwd)/build
-          # mkdir -p ${BUILD_DIR}
-          # # Install to /tmp/ to ensure independent from the CMake build in standalone check.
-          # export INSTALL_DIR=/tmp/ftorch-install
-          # mkdir -p ${INSTALL_DIR}
-          # # NOTE: The pFUnit version (pinned during installation above) is used in the install path.
-          # VN="${{ matrix.pfunit_version }}"
-          # export PFUNIT_DIR="$(pwd)/pFUnit/build/installed/PFUNIT-${VN::-2}"
-          # cd ${BUILD_DIR}
-          # cmake .. \
-          #   -DPython_EXECUTABLE="$(which python)" \
-          #   -DCMAKE_BUILD_TYPE=Release \
-          #   -DCMAKE_Fortran_COMPILER=gfortran  \
-          #   -DCMAKE_C_COMPILER=gcc  \
-          #   -DCMAKE_CXX_COMPILER=g++  \
-          #   -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
-          #   -DCMAKE_BUILD_TESTS=TRUE \
-          #   -DCMAKE_PREFIX_PATH="${PFUNIT_DIR};${Torch_DIR}" \
-          #   -DCMAKE_Fortran_FLAGS="-std=${FORTRAN_STANDARD}"
-          # cmake --build .
-          # cmake --install .
+          TODO: Re-enable CMake build system
+          export BUILD_DIR=$(pwd)/build
+          mkdir -p ${BUILD_DIR}
+          # Install to /tmp/ to ensure independent from the CMake build in standalone check.
+          export INSTALL_DIR=/tmp/ftorch-install
+          mkdir -p ${INSTALL_DIR}
+          # NOTE: The pFUnit version (pinned during installation above) is used in the install path.
+          VN="${{ matrix.pfunit_version }}"
+          export PFUNIT_DIR="$(pwd)/pFUnit/build/installed/PFUNIT-${VN::-2}"
+          cd ${BUILD_DIR}
+          cmake .. \
+            -DPython_EXECUTABLE="$(which python)" \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DCMAKE_Fortran_COMPILER=gfortran  \
+            -DCMAKE_C_COMPILER=gcc  \
+            -DCMAKE_CXX_COMPILER=g++  \
+            -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
+            -DCMAKE_BUILD_TESTS=TRUE \
+            -DCMAKE_PREFIX_PATH="${PFUNIT_DIR};${Torch_DIR}" \
+            -DCMAKE_Fortran_FLAGS="-std=${FORTRAN_STANDARD}"
+          cmake --build .
+          cmake --install .
 
+      - name: Build FTorch with fpm
+        if: ${{ matrix.build_system == fpm }}
+        env:
+          FORTRAN_STANDARD: ${{ matrix.std }}
+        run: |
+          . ftorch/bin/activate
+          VN=$(python -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
+          export Torch_DIR=${VIRTUAL_ENV}/lib/python${VN}/site-packages/torch
           fpm build \
             --profile debug \
             --compiler gfortran \
@@ -172,71 +183,91 @@ jobs:
             --cxx-flag "-cpp -std=c++17 -I${Torch_DIR}/include -I${Torch_DIR}/include/torch/csrc/api/include" \
             --link-flag "-L${Torch_DIR}/lib" \
             --verbose
-          # TODO: --link-flag "-L${Torch_DIR}/lib -L${PFUNIT_DIR}/lib" \
 
-      # TODO: Re-enable pkg-config
-      # - name: Check pkg-config file 
-      #   run: |
-      #     # pkg-config looks in the `build` directory for libraries
-      #     export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:build
+      - name: Check pkg-config file
+        run: |
+          # pkg-config looks in the `build` directory for libraries
+          export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:build
 
-      #     libs=$(pkg-config --libs ftorch)
-      #     cflags=$(pkg-config --cflags ftorch)
+          libs=$(pkg-config --libs ftorch)
+          cflags=$(pkg-config --cflags ftorch)
 
-      #     # Assert linker flags not empty
-      #     if [[ -z "${libs}" ]]
-      #     then
-      #       echo "::error ::pkg-config --libs ftorch returned empty output"
-      #       exit 1
-      #     fi
+          # Assert linker flags not empty
+          if [[ -z "${libs}" ]]
+          then
+            echo "::error ::pkg-config --libs ftorch returned empty output"
+            exit 1
+          fi
 
-      #     # Assert expected linker flags
-      #     lib_dir=$(grep -oE "\-L.*/lib" <<< ${libs})
-      #     lib=$(grep -oE "\-lftorch" <<< ${libs})
-      #     if [[ -z "${lib_dir}" || -z "${lib}" ]]
-      #     then
-      #       echo "::error ::pkg-config --libs ftorch do not contain expected linker flags"
-      #       exit 1
-      #     fi
+          # Assert expected linker flags
+          lib_dir=$(grep -oE "\-L.*/lib" <<< ${libs})
+          lib=$(grep -oE "\-lftorch" <<< ${libs})
+          if [[ -z "${lib_dir}" || -z "${lib}" ]]
+          then
+            echo "::error ::pkg-config --libs ftorch do not contain expected linker flags"
+            exit 1
+          fi
 
-      #     # Assert compiler flags not empty
-      #     if [[ -z "${cflags}" ]]
-      #     then
-      #       echo "::error ::pkg-config --cflags ftorch returned empty output"
-      #       exit 1
-      #     fi
+          # Assert compiler flags not empty
+          if [[ -z "${cflags}" ]]
+          then
+            echo "::error ::pkg-config --cflags ftorch returned empty output"
+            exit 1
+          fi
 
-      #     # Assert expected compiler flags
-      #     include_dir=$(grep -oE "/include " <<< ${cflags})
-      #     module_dir=$(grep -oE "/include/ftorch" <<< ${cflags})
-      #     if [[ -z ${include_dir} || -z ${module_dir} ]]
-      #     then
-      #         echo "::error ::pkg-config --cflags ftorch do not contain expected compiler flags"
-      #         exit 1
-      #     fi
+          # Assert expected compiler flags
+          include_dir=$(grep -oE "/include " <<< ${cflags})
+          module_dir=$(grep -oE "/include/ftorch" <<< ${cflags})
+          if [[ -z ${include_dir} || -z ${module_dir} ]]
+          then
+              echo "::error ::pkg-config --cflags ftorch do not contain expected compiler flags"
+              exit 1
+          fi
 
-      # TODO: Re-enable unit tests
-      # - name: Run Fortran unit tests
-      #   run: |
-      #     . ftorch/bin/activate
-      #     cd build
-      #     ctest --verbose --tests-regex unit
+      - name: Run Fortran unit tests
+        if: ${{ matrix.build_system == cmake }}
+        run: |
+          . ftorch/bin/activate
+          cd build
+          ctest --verbose --tests-regex unit
 
-      # TODO: Re-enable unit tests
-      # - name: Run Python unit tests
-      #   run: |
-      #     . ftorch/bin/activate
-      #     pytest --verbose test/ftorch_utils
+      - name: Run Python unit tests
+        if: ${{ matrix.build_system == cmake }}
+        run: |
+          . ftorch/bin/activate
+          pytest --verbose test/ftorch_utils
 
-      # TODO: Re-enable integration tests
-      # - name: Run integration tests
-      #   run: |
-      #     . ftorch/bin/activate
-      #     cd build
-      #     ctest --verbose --tests-regex example
+      - name: Run integration tests
+        if: ${{ matrix.build_system == cmake }}
+        run: |
+          . ftorch/bin/activate
+          cd build
+          ctest --verbose --tests-regex example
 
         # Check that we can successfully build and run an example outside the main FTorch build process
-      - name: Standalone Tensor example
+      - name: Standalone Tensor example with CMake
+        if: ${{ matrix.build_system == cmake }}
+        env:
+          FORTRAN_STANDARD: ${{ matrix.std }}
+        run: |
+          . ftorch/bin/activate
+          VN=$(python -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
+          export Torch_DIR="${VIRTUAL_ENV}/lib/python${VN}/site-packages/torch"
+          export FTORCH_INSTALL_DIR="/tmp/ftorch-install"
+          export EXAMPLE_BUILD_DIR="examples/02_SimpleNet/build"
+          mkdir "${EXAMPLE_BUILD_DIR}"
+          cd "${EXAMPLE_BUILD_DIR}"
+          cmake .. \
+            -DPython_EXECUTABLE="$(which python)" \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DCMAKE_PREFIX_PATH="${FTORCH_INSTALL_DIR};${Torch_DIR}" \
+            -DCMAKE_BUILD_TESTS=TRUE \
+            -DCMAKE_Fortran_FLAGS="-std=${FORTRAN_STANDARD}"
+          cmake --build .
+          ctest -V
+
+      - name: Standalone Tensor example with fpm
+        if: ${{ matrix.build_system == fpm }}
         env:
           FORTRAN_STANDARD: ${{ matrix.std }}
         run: |
